keycloak:
  extraEnv: |
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: changeme
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      kubernetes.io/ingress.class: nginx
    rules:
      - host: "auth.casd.local"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - auth.casd.local

  postgresql:
    enabled: false
