apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNHRENDQWI2Z0F3SUJBZ0lVRUJHVFZiR0w1am9oTk84alh3WWVDSTVTSDdjd0NnWUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1JsSXhFVEFQQmdOVkJBY1RDRTFoYkdGcmIyWm1NUnN3R1FZRFZRUUtFeEpEUVZORQpJRlJ5ZFhOMElGTmxjblpwWTJVeEdUQVhCZ05WQkFNVEVFTkJVMFFnYXpoeklGSlBUMVFnUTBFd0hoY05Nakl4Ck1ERXlNRGN5TURBd1doY05NamN4TURFeE1EY3lNREF3V2pCWU1Rc3dDUVlEVlFRR0V3SkdVakVSTUE4R0ExVUUKQnhNSVRXRnNZV3R2Wm1ZeEd6QVpCZ05WQkFvVEVrTkJVMFFnVkhKMWMzUWdVMlZ5ZG1salpURVpNQmNHQTFVRQpBeE1RUTBGVFJDQnJPSE1nVWs5UFZDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRVZ6CjJ3bUhFZElJcEFZbTNkU2cvcDhQVGhDM2NBU0RyYnNYMHFUcGNBRWVVOEpZdGt4aGhUMVdRSnA1WE1sRDJZRGUKekNXcTJ4cmN3MnNqb2ZjUlExdWpaakJrTUE0R0ExVWREd0VCL3dRRUF3SUJCakFTQmdOVkhSTUJBZjhFQ0RBRwpBUUgvQWdFQ01CMEdBMVVkRGdRV0JCU1BNcTF0NzJGZVBHZkhhU1dHNjZGQWlyTUFEREFmQmdOVkhTTUVHREFXCmdCU1BNcTF0NzJGZVBHZkhhU1dHNjZGQWlyTUFEREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFWblV6cHBMekgKSUlDVFcxMjduSS9SZ1UyVXM5RlpLQVdOelphN1Bpc2VLUUloQUx1K1VjUE4xS1hMNEVmdUxzZ1pGT2NtUE1CSAptNmdZT0tvZzJqZ2hXRlN6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  creationTimestamp: "2022-10-21T12:56:35Z"
  name: casd-ca
  namespace: casd-minio
  resourceVersion: "7155264"
  uid: cb408d0d-0b99-4615-bdcc-28f44a53308c
type: Opaque
