apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: casd-minio
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$binary_remote_addr"
spec:
  tls:
    - hosts:
        - minio-console.casd.local
  rules:
    - host: minio-console.casd.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: casd-minio-console
                port:
                  number: 9443

