apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: casd-minio
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - minio.casd.local
        - "*.minio.casd.local"
  rules:
    - host: minio.casd.local
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: minio
                port:
                  number: 443
    - host: "*.minio.casd.local"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: minio
                port:
                  number: 443