apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlN6Q0I4Z0lCQURCWU1Rc3dDUVlEVlFRR0V3SkdVakVSTUE4R0ExVUVCeE1JVFdGc1lXdHZabVl4R3pBWgpCZ05WQkFvVEVrTkJVMFFnVkhKMWMzUWdVMlZ5ZG1salpURVpNQmNHQTFVRUF4TVFRMEZUUkNCck9ITWdVazlQClZDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRVZ6MndtSEVkSUlwQVltM2RTZy9wOFAKVGhDM2NBU0RyYnNYMHFUcGNBRWVVOEpZdGt4aGhUMVdRSnA1WE1sRDJZRGV6Q1dxMnhyY3cyc2pvZmNSUTF1ZwpPREEyQmdrcWhraUc5dzBCQ1E0eEtUQW5NQ1VHQTFVZEVRUWVNQnlDQ21OaGMyUXViRzlqWVd5Q0RuZDNkeTVqCllYTmtMbXh2WTJGc01Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRG1jU0ZCcDNXY2U3WEJ5YzlxWDQxUXNkTDIKRzlWSk9ZL00yMitEQk55RVhRSWdFdVN2QjFTUkVaL1Frbk4xR21pNGsvNGhpTXljNnhrUjIyVk9EUFkyMnM4PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLQ==
kind: Secret
metadata:
  creationTimestamp: "2022-10-21T12:56:35Z"
  name: operator-ca-tls
  namespace: minio-operator
type: Opaque