## MinIO Tenant Definition
tenant:
  # Tenant name
  name: casd-minio
  ## Registry location and Tag to download MinIO Server image
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2022-10-05T14-58-27Z
    pullPolicy: IfNotPresent
  ## Customize any private registry image pull secret.
  ## currently only one secret registry is supported
  imagePullSecret: { }
  ## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
  ## If not specified, the Tenant pods will be dispatched by default scheduler.
  scheduler: { }
  ## Secret name that contains additional environment variable configurations.
  ## The secret is expected to have a key named config.env containing environment variables exports.
  configuration:
    name: minio-secret
  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
    ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
    ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
    ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1
      ## custom name for the pool
      name: pool-0
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 1
      ## size specifies the capacity per volume
      size: 100Gi
      ## storageClass specifies the storage class name to be used for this pool
      storageClassName: directpv-min-io
      ## Used to specify annotations for pods
      annotations: { }
      ## Used to specify labels for pods
      labels: { }
      tolerations:
        - key: "storage-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      ## Run pods specifically on storage nodes
      nodeSelector:
        storage-node: "true"
      ## Affinity settings for MinIO pods. Read more about affinity
      ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
      affinity: { }
      ## Configure resource requests and limits for MinIO containers
      resources: { }
      ## Configure security context
      securityContext: { }
      ## Configure topology constraints
      topologySpreadConstraints: [ ]
      ## Configure Runtime Class
      # runtimeClassName: ""
  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  ## Sub path inside Mount path where MinIO stores data.
  subPath: /data
  certificate:
    ## Use this field to provide one or more external CA certificates. This is used by MinIO
    ## to verify TLS connections with other applications:
    ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
    externalCaCertSecret: [ ]
    ## Use this field to provide a list of Secrets with external certificates. This can be used to configure
    ## TLS for MinIO Tenant pods. Create secrets as explained here:
    ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
    externalCertSecret: [ ]
    ## Enable automatic Kubernetes based certificate generation and signing as explained in
    ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
    requestAutoCert: true
    certConfig:
      commonName: "minio-datanode"
      organizationName: []
      dnsNames: []
  # pool metrics to be read by Prometheus
  ## Environment variables for Onyxia's Keycloak integration
  prometheus:
    image: "" # defaults to quay.io/prometheus/prometheus:latest
    env: [ ]
    sidecarimage: "" # defaults to alpine
    initimage: "" # defaults to busybox:1.33.1
    diskCapacityGB: 1
    storageClassName: directpv-min-io
    annotations: { }
    labels: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity:
      nodeAffinity: { }
      podAffinity: { }
      podAntiAffinity: { }
    resources: { }
    serviceAccountName: ""
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
  ## LogSearch API setup for MinIO Tenant.
  log:
    image: "" # defaults to minio/operator:v4.4.17
    env: [ ]
    resources: { }
    nodeSelector: { }
    affinity:
      nodeAffinity: { }
      podAffinity: { }
      podAntiAffinity: { }
    tolerations: [ ]
    annotations: { }
    labels: { }
    audit:
      diskCapacityGB: 1
    ## Postgres setup for LogSearch API
    db:
      image: "" # defaults to library/postgres
      env: [ ]
      initimage: "" # defaults to busybox:1.33.1
      volumeClaimTemplate:
        metadata: { }
        spec:
          storageClassName: directpv-min-io
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

  env:
     # keycloak url realms name=casd-onyxia
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://keycloak-http.keycloak.svc.cluster.local:8443/auth/realms/casd-onyxia/.well-known/openid-configuration"
      # keycloak minio client id
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "minio"
    ## Actually not used but cannot be removed for some reason
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: "2hDziRmwqtZ5jNmTqEmetq9aJ6Q94x3M"
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "policy"
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
      value: "https://minio-console.casd-minio.svc.cluster.local:9443/oauth_callback"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid, profile, email, roles"
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "policy"
    - name: MINIO_DOMAIN
      value: "minio.casd.local"
    - name: MINIO_BROWSER
      value: "on" # to turn-off browser
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://casd-minio-console.casd-minio.svc.cluster.local:9443"
    - name: MINIO_SERVER_URL
      value: "https://minio.casd-minio.svc.cluster.local:443"
## Ingress configuration to expose the API and console services
ingress:
  api:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      # The following annotation is required to let MinIO communicate with the NGINX Ingress controller
      # when using external certificates. See Knowledge base: 8dc2998d-5699-4be6-bed0-b2384a87fe9e
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
      - hosts:
          - minio.casd.local
    host: minio.casd.local
    path: /
    pathType: Prefix
  console:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    tls:
      - hosts:
          - minio-console.casd.local
    host: minio-console.casd.local
    path: /
    pathType: Prefix